version: '2.1'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  flink:
    image: apache/flink:1.16.1
    command:
      - bash
      - -c
      - "./bin/start-cluster.sh; while true; do sleep 10; done"
    ports:
      - "8081:8081"
    volumes:
      - "flink_data:/tmp/flink"
      - "./data:/tmp/data"

volumes:
  flink_data:
    driver: local
